### ISSUE TITLE
Найти датасет по классификации персонажей из доты

### ISSUE THREAD

**Issue by Homry** [moevm/mse1h2024-cv-tasks#34]

**Comment by Margo63** [comment]
Датасеты с информацией про героев
https://www.kaggle.com/datasets/psychewolf/dota-2-heroes-dataset?select=all_heroes.json
https://www.kaggle.com/datasets/prokid1911/dota-2-all-hero-data-727d
https://www.kaggle.com/datasets/nihalbarua/dota2-competitive-picks?select=Current_Pro_meta.csv
Датасет с анализом
https://www.kaggle.com/code/scarfsman/dota-2-competitive-picks-eda
https://www.kaggle.com/datasets/naqeebali/dota2-heroes-pick-rate-and-win-rate-by-mmr

**Comment by Homry** [comment]
Поискать датасет с картинками персонажей

**Comment by Margo63** [comment]
классификация покемонов
https://github.com/bochendong/few_shot_classification/tree/main
классификация покемонов по типу
https://github.com/rileynwong/pokemon-images-dataset-by-type/tree/master

**Comment by Margo63** [comment]
Просто картинки покемонов
https://www.kaggle.com/datasets/kvpratama/pokemon-images-dataset/data
